### ISSUE TITLE
Processes counter is not working properly

### ISSUE THREAD

**Issue by jvendrell** [vilanovailageltru/decidim-vilanova#22]
The Processes page indicates that there are 3 processes. However, you can see 6 processes underneath.

<img width="1440" alt="screen shot 2017-03-21 at 10 36 35" src="https://cloud.githubusercontent.com/assets/7082300/24141039/5e6e007e-0e22-11e7-9acb-21e61fb142b1.png">

**Comment by jvendrell** [comment]
Not really an issue... this section is showing processes and groups of processes at the same time. The counter is counting only the processes. It's confusing, though

**Comment by mrcasals** [comment]
This issue was moved to AjuntamentdeBarcelona/decidim#1190

**Comment by mrcasals** [comment]
Hi! This looks like an issue coming from main decidim, I've opened an issue there so that we can tackle this problem:

https://github.com/AjuntamentdeBarcelona/decidim/issues/1190

Would you like to send us a PR to help us with this issue? :)

**Comment by mrcasals** [comment]
@jvendrell @xredo we fixed this in https://github.com/AjuntamentdeBarcelona/decidim/pull/1213, you might want to update the included gem so that you get this changes (although you will get a lot of other changes too) :)

**Comment by xredo** [comment]
Thank you @mrcasals 🎉🎉🎉 We'll update the dependency as soon as we can update the Ruby version used in the project. As far as I've seen, you are only giving support to the last released Ruby version, making it difficult sometimes to upgrade.

**Comment by mrcasals** [comment]
Oh, that's right. The thing is, since the code is not yet on a stable version we might break some things in the process, but I think we'll get to a stable point soon enough. Meanwhile, would you like to open an issue for this at the decidim repo so we can discuss what Ruby versions should we support? :)

**Comment by mrcasals** [comment]
Oh, that's right @xredo. The thing is, since the code is not yet on a stable version we might break some things in the process, but I think we'll get to a stable point soon enough. Meanwhile, would you like to open an issue for this at the decidim repo so we can discuss what Ruby versions should we support? :)
